apiVersion: v2
name: platform-app
description: Umbrella chart for MLOps Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: argo-cd
    version: 5.51.6
    repository: https://argoproj.github.io/argo-helm
  # PostgreSql for Flyte (Metadata)
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  # MinIO for Flyte (Object Store)
  - name: minio
    version: 5.0.2
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: kubeflow-pipelines
    version: 2.3.0
    repository: https://getindata.github.io/helm-charts
    condition: kubeflow.enabled
  - name: flyte-core
    version: v1.10.0
    repository: https://flyteorg.github.io/flyte
    condition: flyte.enabled
  - name: kserve
    version: 0.12.0
    repository: oci://ghcr.io/kserve/charts
    condition: kserve.enabled
